### PR TITLE
feat(theming): include legacymodels in css-variables

### PR DESCRIPTION
**Pull request by julianiff**
- To be used with https://github.com/Frontify/fondue/pull/876 in fondue

### CODE REVIEW

**Comment by julianiff** [comment]
@thisguyscode There was not yet a black token defined. I used there the old values from fondue.

**Comment by julianiff** [comment]
Fondue yes, you can build the branch and npm link it in fondue or copy the dist/css folder into the node_modules/@frontify/fondue-tokens dist/css folder. Also the package.json and the tailwind/tailwind.config.js (sometimes link is for me a bit buggy).  -> also check out this branch in fondue https://github.com/Frontify/fondue/pull/876
Screenshot 2022-07-15 at 09 27 12

**Comment by julianiff** [comment]
For clarify you would need to then link fondue-tokens and fondue with the changes to it. But that I haven't tested out yet, still have to do that :)

**Comment by julianiff** [comment]
Exactly. Some components still use fixed color values and these need to be changed to tokens that have light and dark values. As it can be a lot of work, might be easier to do it one after another indeed :)

**Review by imoutaharik — APPROVED** [review]

**Pull request merged**
